name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract Ngrok
      run: Expand-Archive ngrok.zip
    - name: Authenticate Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    # ✅ Install OpenSSH (Fixed for Windows 10/11)
    - name: Install OpenSSH Server
      run: Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH.Server*' | Add-WindowsCapability -Online

    - name: Start SSH Service
      run: Start-Service sshd

    - name: Allow SSH Through Firewall
      run: New-NetFirewallRule -Name sshd -DisplayName "OpenSSH Server (sshd)" -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22

    - name: Set Runner Password (For SSH Login)
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    # print the ip
    - name: Show Public IP
      run: curl ifconfig.me

    # Create SSH Tunnel with Ngrok
    - name: Create Ngrok SSH Tunnel
      run: .\ngrok\ngrok.exe tcp 22
